version: '3.8'

services:
  strapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi_app
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: strapi_postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      ADMIN_JWT_SECRET: Jxzshlt7HKg0ZxNhoGJthA==
      API_TOKEN_SALT: 8xZ6eR8Y0F6J12xas+5LHg==
      TRANSFER_TOKEN_SALT: BmKOus2oWxIJMY9DUf5eXA==
      ENCRYPTION_KEY: Ob0xsmOsx4WrAL4Ta7xsFsHyvChDyN9Y1ohyTHU728w=
    volumes:
          - ./src/config:/opt/app/config
          - ./src/src:/opt/app/src
          - ./src/package.json:/opt/package.json
          - ./src/yarn.lock:/opt/yarn.lock
          - ./.env:/opt/app/.env
          - ./src/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi-net
    depends_on:
      - strapi_postgres

  strapi_postgres:
    image: postgres:15
    container_name: strapi_postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-net
  
  nginx:
    image: nginx:alpine
    container_name: strapi_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - strapi_app
    networks:
      - strapi-net

volumes:
  pgdata:

networks:
  strapi-net:
    external: true
